database:
  image: registry.gov.pf/docker/postgres
  environment:
    POSTGRES_DB: turama
    POSTGRES_USER: turama
    POSTGRES_PASSWORD: turama

turama:
  image: sipf/turama
  links:
    - database
  ports:
    - 8080:8080

