database:
  image: registry.gov.pf/docker/postgres
  environment:
    POSTGRES_DB: turama
    POSTGRES_USER: turama
    POSTGRES_PASSWORD: turama

turama:
  image: registry.gov.pf/docker/turama
  links:
    - database
  ports:
    - ${public_port}:8080

