postgres-rails:
  environment:
    POSTGRES_USER: ${postgres_rails_user}
    POSTGRES_PASSWORD: ${postgres_rails_password}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  image: postgres:9.5
  stdin_open: true
website:
  log_driver: syslog
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: logging=true
  tty: true
  log_opt:
    syslog-address: udp://${logstash_link}:5000
  image: registry.gov.pf/${containers_default_project}/lemoteur:website
  links:
  - elastic-rails:elasticsearch
  - postgres-rails:postgres-rails
  - cable-rails:cable-rails
  - redis-rails:redis-rails
  stdin_open: true
cable-rails:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  command:
  - puma
  - -p
  - '28080'
  - cable/config.ru
  image: registry.gov.pf/${containers_default_project}/lemoteur:cable-rails
  links:
  - redis-rails:redis-rails
  stdin_open: true
elastic-rails:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  image: elasticsearch:2.4
  stdin_open: true
  volumes:
  - elastic-rails:/var/lib/elasticsearch/data
lb:
  ports:
  - 80:3000
  tty: true
  image: rancher/load-balancer-service
  links:
  - website:website
  stdin_open: true
redis-rails:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  command:
  - redis-server
  - --requirepass
  - ${redis_rails_password}
  image: redis:3.2-alpine
  stdin_open: true

