webapp:
  image: registry.gov.pf/net/lemoteur:website-ref
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: pf.gov.docker.tier=${webapp_label}
  tty: true
  external_links:
    - ${elasticsearch_link}:elasticsearch
    - ${postgres_link}:postgres
    - ${redis_link}:redis
    - ${logstash_link}:logstash
  stdin_open: true

sidekiq:
  image: registry.gov.pf/net/lemoteur:sidekiq-ref
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: pf.gov.docker.tier=${webapp_label}
  command: bundle exec sidekiq
  external_links:
    - ${elasticsearch_link}:elasticsearch
    - ${postgres_link}:postgres
    - ${redis_link}:redis
    - ${logstash_link}:logstash
