postgres-rails:
  environment:
    POSTGRES_USER: ${postgres_rails_user}
    POSTGRES_PASSWORD: ${postgres_rails_password}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  image: postgres:9.5
  stdin_open: true
kibana-elk:
  ports:
  - 5601:5601/tcp
  environment:
    ELASTICSEARCH_URL: http://elasticsearch-elk:9200
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  image: registry.gov.pf/blot/lemoteur:kibana-elk
  links:
  - elasticsearch-elk:elasticsearch-elk
  stdin_open: true
website:
  log_driver: syslog
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: logging=true
  tty: true
  log_opt:
    syslog-address: tcp://localhost:5000
  image: registry.gov.pf/blot/lemoteur:website
  links:
  - elastic-rails:elasticsearch
  - postgres-rails:postgres-rails
  - cable-rails:cable-rails
  - redis-rails:redis-rails
  stdin_open: true
logstash-elk:
  ports:
  - 5000:5000/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: logging=true
  tty: true
  command:
  - -f
  - /opt/logstash/conf.d/logstash.conf
  image: registry.gov.pf/blot/lemoteur:logstash-elk
  links:
  - elasticsearch-elk:elasticsearch-elk
  stdin_open: true
cable-rails:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  command:
  - puma
  - -p
  - '28080'
  - cable/config.ru
  image: registry.gov.pf/blot/lemoteur:cable-rails
  links:
  - redis-rails:redis-rails
  stdin_open: true
elasticsearch-elk:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  image: registry.gov.pf/blot/lemoteur:elasticsearch-elk
  stdin_open: true
elastic-rails:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  image: elasticsearch:2.4
  stdin_open: true
lb:
  ports:
  - 80:3000
  tty: true
  image: rancher/load-balancer-service
  links:
  - website:website
  stdin_open: true
redis-rails:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  command:
  - redis-server
  - --requirepass
  - ${redis_rails_password}
  image: redis:3.2-alpine
  stdin_open: true

