.catalog:
  name: "SIPF"
  version: "0.1.6"
  description: "Application du gouvernement de la PF"
  uuid: "lemoteur-0.1.6-201609-1"
  minimum_rancher_version: v1.1.3
  questions:
    - variable: public_port
      description: "Public port to expose the service (useless)"
      label: "Port public"
      type: "int"
      required: true
      default: 8081

postgres-rails:
  scale: 1
kibana-elk:
  scale: 1
website:
  scale: 1
logstash-elk:
  scale: 1
cable-rails:
  scale: 1
elasticsearch-elk:
  scale: 1
elastic-rails:
  scale: 1
redis-rails:
  scale: 1
lb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
