.catalog:
  name: "lemoteur"
  version: "0.2.4"
  description: "Le moteur de recherche"
  minimum_rancher_version: v1.1.3
  questions:
    - variable: "logstash_link"
      description: |
        stack/service link or external service link to logstash.
      default: "log-endpoint/logstash-collector"
      required: true
      type: "service"
    - variable: "elasticsearch_link"
      description: |
        stack/service link or external service link to elasticsearch.
      default: "app-index/elasticsearch-clients"
      required: true
      type: "service"
    - variable: "postgres_link"
      description: |
        stack/service link or external service link to postgres.
      default: "app-database/postgres"
      required: true
      type: "service"
    - variable: "redis_link"
      description: |
        stack/service link or external service link to redis.
      default: "app-cache/redis"
      required: true
      type: "service"
    - variable: webapp_label
      description: "Label to place the webapp stack on the right environment."
      label: "webapp label"
      type: "string"
      required: true
      default: 'backend'

webapp:
  scale: 1
  health_check:
    port: 3000
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000

sidekiq:
  scale: 1
