.catalog:
  name: "lemoteur"
  version: "0.2.0"
  description: "Le moteur de recherche"
  minimum_rancher_version: v1.1.3
  questions:
    - variable: postgres_rails_user
      description: "Postgres user account to use to connect to postgres-rails database service"
      label: "postgres-rails user account"
      type: "string"
      required: true
      default: "lemoteur"
    - variable: postgres_rails_password
      description: "Postgres user password to use to connect to postgres-rails database service"
      label: "postgres-rails user password"
      type: "password"
      required: true
      default: "yourpassword"
    - variable: redis_rails_password
      description: "Redis password to use to connect to redis-rails key-value service"
      label: "redis-rails user password"
      type: "password"
      required: true
      default: "yourpassword"
    - variable: containers_default_project
      description: "Container's default project"
      label: "Containers project (default: net)"
      type: "string"
      required: true
      default: "net"
    - variable: "logstash_link"
      description: |
        stack/service link or external service link to logstash.
      default: "logstash/logstash-collector"
      required: true
      type: "service"

website:
  scale: 1
  health_check:
    port: 3000
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
postgres-rails:
  scale: 1
  health_check:
    port: 5432
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
cable-rails:
  scale: 1
  health_check:
    port: 28080
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
elastic-rails:
  scale: 1
  health_check:
    port: 9200
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
redis-rails:
  scale: 1
  health_check:
    port: 6379
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
lb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
