.catalog:
  name: "postgres"
  version: "0.1.0"
  description: "The PostgreSQL object-relational database system provides reliability and data integrity."
  minimum_rancher_version: v1.1.3
  questions: 
    - variable: postgres_label
      description: "Label to place postgres database server on the right environment."
      label: "postgres label"
      type: "string"
      required: true
      default: 'database'
    - variable: postgres_db_name
      description: "PostgreSQL database name."
      label: "postgres database name"
      type: "string"
      required: true
    - variable: postgres_db_user
      description: "PostgreSQL database user."
      label: "postgres database user"
      type: "string"
      required: true
    - variable: postgres_db_password
      description: "PostgreSQL user password."
      label: "postgres user password"
      type: "password"
      required: true

postgres:
  scale: 1
  health_check:
    port: 5432
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 3
    response_timeout: 5000
