database:
  environment:
    MYSQL_ROOT_PASSWORD: 'connfa'
    MYSQL_DATABASE:      'connfa'
    MYSQL_USER:          'connfa'
    MYSQL_PASSWORD:      'connfa'
  image: 'mysql:5.6'
  labels:
    io.rancher.scheduler.affinity:host_label: pf.gov.docker.tier=${database_label}
  container_name: 'database'

cache:
  image: 'redis:3.2-alpine'
  command: redis-server --requirepass yourpassword
  labels:
    io.rancher.scheduler.affinity:host_label: pf.gov.docker.tier=${backend_label}
  container_name: 'cache'

api:
  image: registry.gov.pf/net/connfa-api:latest
  labels:
    io.rancher.scheduler.affinity:host_label: pf.gov.docker.tier=${backend_label}
  container_name: 'api'
  environment:
    WEBROOT: '/var/www/html/public'
    DOMAIN: 'api.net.pf'
  ports:
    - '80:80/tcp'
  links:
    - database:database
    - cache:cache
