.catalog:
  name: "connfa"
  version: "0.1.0"
  description: "Conference API"
  questions:
    - variable: "backend_label"
      label: "backend label"
      description: "Label to place backend on the right environment."
      type: "string"
      default: 'backend'
      required: true
    - variable: "database_label"
      label: "database label"
      description: "Label to place database on the right environment."
      type: "string"
      default: 'database'
      required: true

mysql:
  scale: 1
  health_check:
    port: 3306
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 5000
    healthy_threshold: 3

redis:
  scale: 1
  health_check:
    port: 6379
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 3
    response_timeout: 5000

api:
  scale: 1
  health_check:
    port: 80
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 5000
    healthy_threshold: 3
