name: elasticsearch
description: |
  Elasticsearch. You know, for search
version: 0.1.0
category: Applications
maintainer: Leonard TAVAE
license: MIT
projectURL: https://github.com/sitle/rancher-templates
