application:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: ${perliprog_container}
  links:
  - cache:cache
  stdin_open: true
cache:
  environment:
    MYSQL_ROOT_PASSWORD: ${cache_db_password}
    MYSQL_DATABASE: ${cache_db_name}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: registry.gov.pf/docker/mysql
  stdin_open: true
