.catalog:
  name: "SIPF"
  version: "0.1.2"
  description: "Application du gouvernement de la PF"
  uuid: "selenium-0.1.3-201609-1"
  minimum_rancher_version: v1.1.3

hub:
  scale: 1
  health_check:
    port: 4444
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 5000
    healthy_threshold: 3

node:
  scale: 4
  health_check:
    port: 4444
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 3
    response_timeout: 5000
