version: '2'
volumes:
  icescrum-app:
    external: true
    driver: 'null'
  icescrum-postgres:
    external: true
    driver: 'null'
services:
  database:
    image: registry.gov.pf/docker/postgres
    environment:
      POSTGRES_DB: icescrum
      POSTGRES_PASSWORD: mysupericescrum
      POSTGRES_USER: icescrum
    stdin_open: true
    volumes:
    - icescrum-postgres:/var/lib/postgresql/data
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: pf.gov.docker.tier=${database_label}
  application:
    image: icescrum/icescrum
    environment:
      ICESCRUM_CONTEXT: /
      ICESCRUM_HOST: ${host_ip}
      ICESCRUM_PORT: '80'
    stdin_open: true
    volumes:
    - icescrum-app:/root
    tty: true
    links:
    - database:postgres
    expose:
    - '80'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: pf.gov.docker.tier=${application_label}
  reverse:
    image: rancher/lb-service-haproxy:v0.4.6
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity:host_label: pf.gov.docker.tier=${loadbalancer_label}
