database:
  image: registry.gov.pf/docker/postgres
  tty: true
  stdin_open: true
  environment:
    POSTGRES_DB: icescrum
    POSTGRES_USER: icescrum
    POSTGRES_PASSWORD: mysupericescrum
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  volumes:
    - icescrum-postgres:/var/lib/postgresql/data

application:
  image: icescrum/icescrum
  tty: true
  stdin_open: true
  environment:
    ICESCRUM_HOST: 10.0.0.247
    ICESCRUM_PORT: 80
    ICESCRUM_CONTEXT: /
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  expose:
    - 80
  links:
    - database:postgres
  #volumes:
  #  - icescrum-app:/root

lb:
  image: rancher/load-balancer-service
  tty: true
  stdin_open: true
  labels:
    io.rancher.scheduler.affinity:host_label: loadbalancer.domain=true
  ports:
    - 80:80

