version: '2'
volumes:
  icescrum-app:
    external: true
    driver: 'null'
  icescrum-postgres:
    external: true
    driver: 'null'
services:
  database:
    image: registry.gov.pf/docker/postgres
    environment:
      POSTGRES_DB: icescrum
      POSTGRES_PASSWORD: mysupericescrum
      POSTGRES_USER: icescrum
    stdin_open: true
    volumes:
    - icescrum-postgres:/var/lib/postgresql/data
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: pf.gov.docker.tier=${database_label}
  dev:
    image: icescrum/icescrum
    environment:
      ICESCRUM_CONTEXT: /
      ICESCRUM_HOST: ${host_ip}
      ICESCRUM_PORT: '8080'
    stdin_open: true
    volumes:
    - icescrum-app:/root
    tty: true
    links:
    - database:postgres
    ports:
    - '8080:8080/tcp'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: pf.gov.docker.tier=${application_label}
      traefik.enable: true
      traefik.domain: gov.pf
      traefik.port: '8080'
