.catalog:
  name: "icescrum"
  version: "0.1.1"
  description: "Logiciel icescrum"
  minimum_rancher_version: v1.1.3
  questions:
    - variable: "host_ip"
      description: "Adresse IP de l'hote hebergeant l'application"
      label: "Host IP"
      type: "string"
      required: true
      default: "10.0.0.247"
    - variable: "database_label"
      label: "database label"
      description: "Label to place database on the right environment."
      type: "string"
      default: 'database'
      required: true
    - variable: "application_label"
      label: "application label"
      description: "Label to place application on the right environment."
      type: "string"
      default: 'application'
      required: true

version: '2'
services:
  database:
    scale: 1
    start_on_create: true
  application:
    scale: 1
    start_on_create: true
