.catalog:
  name: "icescrum"
  version: "0.1.1"
  description: "Logiciel icescrum"
  minimum_rancher_version: v1.1.3
  questions:
    - variable: "host_ip"
      description: "Adresse IP de l'hote hebergeant l'application"
      label: "Host IP"
      type: "string"
      required: true
      default: "dev.icescrum.gov.pf"
    - variable: "database_label"
      label: "database label"
      description: "Label to place database on the right environment."
      type: "string"
      default: 'database'
      required: true
    - variable: "application_label"
      label: "application label"
      description: "Label to place application on the right environment."
      type: "string"
      default: 'application'
      required: true

version: '2'
services:
  database:
    scale: 1
    start_on_create: true
  dev:
    scale: 1
    start_on_create: true
    health_check:
      port: 80
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      response_timeout: 2000
      request_line: GET "/" "HTTP/1.0"
      healthy_threshold: 2
