.catalog:
  name: "icescrum"
  version: "0.1.1"
  description: "Logiciel icescrum"
  minimum_rancher_version: v1.1.3
  questions:
    - variable: "host_ip"
      description: "Adresse IP de l'hote hebergeant l'application"
      label: "Host IP"
      type: "string"
      required: true
      default: "10.0.0.247"
    - variable: "database_label"
      label: "database label"
      description: "Label to place database on the right environment."
      type: "string"
      default: 'database'
      required: true
    - variable: "application_label"
      label: "application label"
      description: "Label to place application on the right environment."
      type: "string"
      default: 'application'
      required: true
    - variable: "loadbalancer_label"
      label: "loadbalancer label"
      description: "Label to place loadbalancer on the right environment."
      type: "string"
      default: 'lb'
      required: true

version: '2'
services:
  database:
    scale: 1
    start_on_create: true
  application:
    scale: 1
    start_on_create: true
  reverse:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: dev.icescrum.gov.pf
        path: ''
        priority: 1
        protocol: http
        service: application
        source_port: 80
        target_port: 8080
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000

