.catalog:
  name: "I-SAV"
  version: "0.1.0"
  description: "Prototype I-SAV"

i-sav:
  scale: 1
  health_check:
    port: 8080
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 3
    response_timeout: 5000