name: SIPF-SELENIUM
description: |
  Architecture cluster pour effectuer des tests applicatifs
version: 0.1.2
category: Applications
maintainer: Leonard TAVAE
license: MIT
projectURL: https://github.com/sitle/rancher-templates
