.catalog:
  name: "SIPF"
  version: "0.1.3"
  description: "Application du gouvernement de la PF"
  uuid: "kong-0.1.3-201611-1"
  minimum_rancher_version: v1.1.3
  questions: 
    - variable: public_port
      description: "Public port to expose the kong dashboard"
      label: "Port public"
      type: "int"
      required: true
      default: 8080
    - variable: "kong_db_label"
      label: "Kong database label"
      description: "Label to place kong database on the right environment."
      type: "string"
      default: 'database'
      required: true
    - variable: "kong_api_label"
      label: "Kong api label"
      description: "Label to place kong api on the right environment."
      type: "string"
      default: 'backend'
      required: true
    - variable: "kong_dashboard_label"
      label: "Kong dashboard label"
      description: "Label to place kong dashboard on the right environment."
      type: "string"
      default: 'backend'
      required: true

kong-database:
  scale: 1

kong:
  scale: 3
  health_check:
    port: 8001
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 3
    response_timeout: 5000

kong-dashboard:
  scale: 1
  health_check:
    port: 8080
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 3
    response_timeout: 5000
