.catalog:
  name: "SIPF"
  version: "0.1.0"
  description: "Application du gouvernement de la PF"
  uuid: "kong-0.1.0-201609-1"
  minimum_rancher_version: v1.1.3
  questions: 
    - variable: public_port
      description: "Public port to expose the kong dashboard"
      label: "Port public"
      type: "int"
      required: true
      default: 8080

kong-database:
  scale: 1

kong:
  scale: 1
  health_check:
    port: 8001
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 3
    response_timeout: 5000

kong-dashboard:
  scale: 1
  health_check:
    port: 8080
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 3
    response_timeout: 5000
